// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: scanner_search_service.proto

package scanner_search_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScannerSearchService_QueryDataWithFilter_FullMethodName = "/grpc.ScannerSearchService/QueryDataWithFilter"
)

// ScannerSearchServiceClient is the client API for ScannerSearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScannerSearchServiceClient interface {
	QueryDataWithFilter(ctx context.Context, in *StrategyFilterRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type scannerSearchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScannerSearchServiceClient(cc grpc.ClientConnInterface) ScannerSearchServiceClient {
	return &scannerSearchServiceClient{cc}
}

func (c *scannerSearchServiceClient) QueryDataWithFilter(ctx context.Context, in *StrategyFilterRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, ScannerSearchService_QueryDataWithFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScannerSearchServiceServer is the server API for ScannerSearchService service.
// All implementations must embed UnimplementedScannerSearchServiceServer
// for forward compatibility.
type ScannerSearchServiceServer interface {
	QueryDataWithFilter(context.Context, *StrategyFilterRequest) (*QueryResponse, error)
	mustEmbedUnimplementedScannerSearchServiceServer()
}

// UnimplementedScannerSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScannerSearchServiceServer struct{}

func (UnimplementedScannerSearchServiceServer) QueryDataWithFilter(context.Context, *StrategyFilterRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDataWithFilter not implemented")
}
func (UnimplementedScannerSearchServiceServer) mustEmbedUnimplementedScannerSearchServiceServer() {}
func (UnimplementedScannerSearchServiceServer) testEmbeddedByValue()                              {}

// UnsafeScannerSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScannerSearchServiceServer will
// result in compilation errors.
type UnsafeScannerSearchServiceServer interface {
	mustEmbedUnimplementedScannerSearchServiceServer()
}

func RegisterScannerSearchServiceServer(s grpc.ServiceRegistrar, srv ScannerSearchServiceServer) {
	// If the following call pancis, it indicates UnimplementedScannerSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScannerSearchService_ServiceDesc, srv)
}

func _ScannerSearchService_QueryDataWithFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerSearchServiceServer).QueryDataWithFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerSearchService_QueryDataWithFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerSearchServiceServer).QueryDataWithFilter(ctx, req.(*StrategyFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScannerSearchService_ServiceDesc is the grpc.ServiceDesc for ScannerSearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScannerSearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ScannerSearchService",
	HandlerType: (*ScannerSearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryDataWithFilter",
			Handler:    _ScannerSearchService_QueryDataWithFilter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scanner_search_service.proto",
}
